name: ${project.name}
main: com.promcteam.codex.CodexEngine
version: ${project.version}
description: Core plugin for the ProMCTeam suite
api-version: '1.16'
load: STARTUP
authors:
  - Travja
  - goflish
has-open-classloader: true
libraries: [ com.mysql:mysql-connector-j:${mysql.version}, org.apache.commons:commons-lang3:${apache.version} ]
provides:
  - ProMCCore

dependencies:
  - name: Vault
    required: false
    bootstrap: true
  - name: WorldGuard
    required: false
    bootstrap: true
  - name: MythicMobs
    required: false
    bootstrap: true
load-before:
  - name: Fabled
    boostrap: false
  - name: Divinity
    boostrap: false