name: ${project.name}
main: com.promcteam.codex.CodexEngine
version: ${project.version}
description: Core plugin for the ProMCTeam suite
authors: [ Travja, goflish ]
softdepend: [ Vault, WorldGuard, MythicMobs ]
api-version: 1.16
load: STARTUP
libraries: [ com.mysql:mysql-connector-j:${mysql.version}, org.apache.commons:commons-lang3:${apache.version} ]
provides: [ ProMCCore ]