name: Build Artifacts

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    uses: magemonkeystudio/.github/.github/workflows/reusable-maven.yml@main
    secrets: inherit
    with:
      maven_args: '-f pom-dev.xml'
      java_version: |
        11
        17
        21

